{% set name = "pandera" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c7654b68ee453f918cf0886b6c6f5e177d7f4e208867684fa7126e19dfc37e9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install simpleeval && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - typing_extensions
    - typing_inspect >=0.6.0
    - wrapt
    - packaging
    - pyarrow

test:
  imports:
    - pandera
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pandera-dev/pandera
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Light-weight and flexible validation for pandas data structures
  description: |
    pandera validates pandas data structures at runtime. This is useful in
    production-critical data pipelines or reproducible research settings.
    pandera-core contains the bare-bones functionality for pandas data
    validation.
  doc_url: https://pandera.readthedocs.io/en/latest/
  dev_url: https://github.com/pandera-dev/pandera

extra:
  recipe-maintainers:
    - cosmicBboy
