{% set name = "pandera" %}
{% set version = "0.18.2" %}

package:
  name: {{ name|lower }}-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 97d3e00e6b8a1ec93e5455c29c826a171028b597fb4d9a625945b8a7ec3b3206

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - multimethod <=1.10.0
    - numpy
    - pandas
    - typing_extensions
    - typeguard >=3.0.2
    - typing_inspect >=0.6.0
    - wrapt
    - packaging
    - pydantic

test:
  imports:
    - pandera
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pandera-dev/pandera
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The open source framework for precision data testing
  description: |
    A simple, zero-configuration Python library to help you build
    confidence in the quality of your dataframe-like containers through
    data validation and property-based testing.
  doc_url: https://pandera.readthedocs.io/en/latest/
  dev_url: https://github.com/unionai-oss/pandera

extra:
  recipe-maintainers:
    - cosmicBboy
