{% set name = "pandera" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}-core
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af3bbaa163672c91b83d59d70715f25c4134dbccfc8bc89a642a2f0e23db951e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=8.0.1
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24.4
    - pandas >=2.1.1
    - typing_extensions
    - typeguard >=3.0.2
    - typing_inspect >=0.6.0
    - packaging
    - pydantic

test:
  imports:
    - pandera
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pandera-dev/pandera
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The open source framework for precision data testing
  description: |
    A simple, zero-configuration Python library to help you build
    confidence in the quality of your dataframe-like containers through
    data validation and property-based testing.
  doc_url: https://pandera.readthedocs.io/en/latest/
  dev_url: https://github.com/unionai-oss/pandera

extra:
  recipe-maintainers:
    - cosmicBboy
