{% set name = "pandera" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}-core
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2afa00945ebe00558b5240c988effff48ec806e3ede6bd19a574f2a5f1abe214

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - numpy >=1.24.4
    - pandas >=2.1.1
    - typeguard >=3.0.2
    - typing_inspect >=0.6.0
    - packaging
    - pydantic

test:
  imports:
    - pandera
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pandera-dev/pandera
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The open source framework for precision data testing
  description: |
    A simple, zero-configuration Python library to help you build
    confidence in the quality of your dataframe-like containers through
    data validation and property-based testing.
  doc_url: https://pandera.readthedocs.io/en/latest/
  dev_url: https://github.com/unionai-oss/pandera

extra:
  recipe-maintainers:
    - cosmicBboy
